### ISSUE TITLE
Base64 images

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [abyssalcode/img64#1]
I see you too are playing around with Base64 images.  Since adding support for them in PySimpleGUI I've been converting more and more images into Base64.  I eventually wrote this program which will convert all ICO, PNG files in a folder into Base64 and writes a single .py file with all  of the files embedded.  Maybe you'll find it useful.

https://github.com/PySimpleGUI/PySimpleGUI/blob/master/DemoPrograms/Demo_Base64_Image_Encoder.py

Was great to see your code using PySimpleGUI.  Hopefully it's working out OK for you.

(Oh, just noticed who checked in the code!  I'm pretty confident PySimpleGUI is working out well for you)

**Comment by eagleEggs** [comment]
Haha yes thanks. I wrote this quickly to convert all the images to base64 and then just keeping it around in case I need it again :)

**Comment by MikeTheWatchGuy** [comment]
Mine has a progress meter that goes so fast that I never really see it except for 1 second regardless of how many there are.  I guess I could add some sleeps to make it more dramatic and make it seem like it's doing something.

**Comment by eagleEggs** [comment]
Cool. I base64'd the base64 like 3 or 4 times on accident... the text file ended up being 3GB. That leads me to see a use for progress bars on larger amounts of images.

**Comment by eagleEggs** [comment]
BTW PSG is rock solid. Great work man. I'm wondering if I should consider some of the spin offs and what the benefits would be. I have no idea what they are, QT and such. Maybe you could elaborate? I did look over the readme's of them but it's not clear if I am using PSG (Which I hope stays your main focus) that I'd need to even move to convert to your other projects and whether the same support would be maintained.

**Comment by MikeTheWatchGuy** [comment]
That's what I like to hear!  Rock Solid is a major, although unstated, goal.  "It just works" is the kind of software I like to use and write.  I do know of some bugs, mostly in the area of styling.

As far as the other versions, PySimpleGUIWx and PySimpleGUIQt.  Each has a slightly different set of features.  Some have more than others.  PySimpleGUI is the most finished.  Qt has slightly less features.  Some of the Graph methods in particular are missing.  As a result, it's in Alpha status.  Wx has the least but looks super promising.

If you want to use the System Tray, then you'll need either the Wx or Qt version.  The tkinter widgets look the most primitive overall.  WxPython has some advanced widgets, like speedometers, that the others don't have.

If you must have an image as the background for your window. then Qt is the only one that can do that.

If you want to turn into an EXE file then you'll have to deal with these sizes.  Minimum size of PySimpleGUI is 8 MB.  PySimpleGUIWx is 10 MB.  PySimpleGUIQt is 240 MB.

So there you go... that's the PySimpleGUI family tree overview.

I'm enjoying Wx overall the best in some ways.  They all suck however, or else I wouldn't have started the project to begin with.  I still they they all suck ;-)  Long live PySimpleGUI!

Oh, PySimpleGUI is not my primary project BTW.  I have a much much much higher priority, secret, project.

**Comment by eagleEggs** [comment]
Thanks for the clarification. I'm good with PSG. My interested is peaked on your secret project...

**Comment by eagleEggs** [comment]
See you next time, on the next 'dancing with the developers.'
